---
repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: no-commit-to-branch
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.30.0
    hooks:
      - id: markdownlint
        files: \.(markdown|md)$

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.17.0
    hooks:
      - id: eslint
        files: \.(js|ts|vue)$

  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: 0.0.2
    hooks:
      - id: stylelint
        files: \.(css|scss)$
        additional_dependencies:
          - "postcss-html@1.4.1"
          - "postcss-scss@4.0.4"
          - "stylelint@14.8.3"
          - "stylelint-config-recess-order@3.0.0"
          - "stylelint-config-prettier@9.0.3"
          - "stylelint-config-standard@25.0.0"
          - "stylelint-scss@4.2.0"
