---

extends:
  - "stylelint-config-standard"
  - "stylelint-config-recess-order"
  - "stylelint-config-prettier"
plugins: ['stylelint-scss']
ignoreFiles: ['**/node_modules/**']
overrides:
  - files: ["**/*.scss"]
    customSyntax: "postcss-scss"
  - files: ["**/*.vue"]
    customSyntax: "postcss-html"
rules:
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - include
        - mixin
        - each
        - use
        - forward
  selector-pseudo-class-no-unknown: null
  selector-pseudo-element-no-unknown: null
